# Generated by Django 5.1.2 on 2024-12-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
