# Generated by Django 5.1.2 on 2024-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Fecha_contratacion', models.DateField(blank=True, null=True)),
                ('Puesto', models.CharField(max_length=50)),
            ],
        ),
    ]
