# Generated by Django 5.1 on 2024-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
